monolog:
  channels:
    - deprecation
    - security_audit
    - operations

when@dev:
  monolog:
    handlers:
      main:
        type: stream
        path: '%kernel.logs_dir%/%kernel.environment%.log'
        level: debug
        channels: ['!event', '!doctrine', '!security_audit', '!operations']
      console:
        type: console
        process_psr_3_messages: false
        channels: ['!event', '!doctrine', '!console']
      security_audit:
        type: stream
        path: '%kernel.logs_dir%/security-audit.log'
        level: info
        channels: ['security_audit']
        formatter: monolog.formatter.json
      operations:
        type: stream
        path: '%kernel.logs_dir%/operations.log'
        level: warning
        channels: ['operations']
        formatter: monolog.formatter.json

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        channels: ['!event']
      nested:
        type: stream
        path: '%kernel.logs_dir%/%kernel.environment%.log'
        level: debug

when@prod:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50
        channels: ['!security_audit', '!operations']
      nested:
        type: stream
        path: 'php://stderr'
        level: debug
        formatter: monolog.formatter.json
      console:
        type: console
        process_psr_3_messages: false
        channels: ['!event', '!doctrine']
      deprecation:
        type: stream
        channels: [deprecation]
        path: 'php://stderr'
        formatter: monolog.formatter.json
      security_audit:
        type: stream
        path: '%kernel.logs_dir%/security-audit.log'
        level: info
        channels: ['security_audit']
        formatter: monolog.formatter.json
      operations:
        type: stream
        path: '%kernel.logs_dir%/operations.log'
        level: warning
        channels: ['operations']
        formatter: monolog.formatter.json
